var products = [{
    ProductID : 1,
    ProductName : "Chai",
    QuantityPerUnit : "10 boxes x 20 bags",
    UnitPrice : 18.0000,
    UnitsInStock : 39,
    UnitsOnOrder : 0,
    ReorderLevel : 10,
    Discontinued : false,
    CategoryName : "Beverages"
    
},
{
    ProductID : 3,
    ProductName : "Aniseed Syrup",
    SupplierID : 1,
    CategoryID : 2,
    QuantityPerUnit : "12 - 550 ml bottles",
    UnitPrice : 10.0000,
    UnitsInStock : 13,
    UnitsOnOrder : 70,
    ReorderLevel : 25,
    Discontinued : false,    
    CategoryName : "Condiments"
    
}

];

var Utilidades = 
     [{ "COD_TRAB": "067552", "TRABAJADOR": "ECHEVARRIA JESUS PAULIÑHO ", "ANIO": 2014, "MES": 1, "MES_NAME": "ENERO", "COD_CONCEPTO": "DIAS", "VALOR": 23, "AFECTO": "DIAS" }, { "COD_TRAB": "067552", "TRABAJADOR": "ECHEVARRIA JESUS PAULIÑHO ", "ANIO": 2014, "MES": 1, "MES_NAME": "ENERO", "COD_CONCEPTO": "121", "VALOR": 2204.17, "AFECTO": "AFECTO" }, { "COD_TRAB": "067552", "TRABAJADOR": "ECHEVARRIA JESUS PAULIÑHO ", "ANIO": 2014, "MES": 1, "MES_NAME": "ENERO", "COD_CONCEPTO": "201", "VALOR": 75, "AFECTO": "AFECTO" }, { "COD_TRAB": "067552", "TRABAJADOR": "ECHEVARRIA JESUS PAULIÑHO ", "ANIO": 2014, "MES": 1, "MES_NAME": "ENERO", "COD_CONCEPTO": "303", "VALOR": 200, "AFECTO": "AFECTO" }, { "COD_TRAB": "067552", "TRABAJADOR": "ECHEVARRIA JESUS PAULIÑHO ", "ANIO": 2014, "MES": 1, "MES_NAME": "ENERO", "COD_CONCEPTO": "118", "VALOR": 670.83, "AFECTO": "AFECTO" }, { "COD_TRAB": "067552", "TRABAJADOR": "ECHEVARRIA JESUS PAULIÑHO ", "ANIO": 2014, "MES": 1, "MES_NAME": "ENERO", "COD_CONCEPTO": "118", "VALOR": 17.5, "AFECTO": "AFECTO" }, { "COD_TRAB": "067552", "TRABAJADOR": "ECHEVARRIA JESUS PAULIÑHO ", "ANIO": 2014, "MES": 1, "MES_NAME": "ENERO", "COD_CONCEPTO": "118", "VALOR": 32.67, "AFECTO": "AFECTO" }, { "COD_TRAB": "067552", "TRABAJADOR": "ECHEVARRIA JESUS PAULIÑHO ", "ANIO": 2014, "MES": 2, "MES_NAME": "FEBRERO", "COD_CONCEPTO": "DIAS", "VALOR": 30, "AFECTO": "DIAS" }, { "COD_TRAB": "067552", "TRABAJADOR": "ECHEVARRIA JESUS PAULIÑHO ", "ANIO": 2014, "MES": 2, "MES_NAME": "FEBRERO", "COD_CONCEPTO": "121", "VALOR": 2875, "AFECTO": "AFECTO" }, { "COD_TRAB": "067552", "TRABAJADOR": "ECHEVARRIA JESUS PAULIÑHO ", "ANIO": 2014, "MES": 2, "MES_NAME": "FEBRERO", "COD_CONCEPTO": "201", "VALOR": 75, "AFECTO": "AFECTO" }, { "COD_TRAB": "067552", "TRABAJADOR": "ECHEVARRIA JESUS PAULIÑHO ", "ANIO": 2014, "MES": 2, "MES_NAME": "FEBRERO", "COD_CONCEPTO": "303", "VALOR": 190, "AFECTO": "AFECTO" }, { "COD_TRAB": "067552", "TRABAJADOR": "ECHEVARRIA JESUS PAULIÑHO ", "ANIO": 2014, "MES": 3, "MES_NAME": "MARZO", "COD_CONCEPTO": "DIAS", "VALOR": 30, "AFECTO": "DIAS" }, { "COD_TRAB": "067552", "TRABAJADOR": "ECHEVARRIA JESUS PAULIÑHO ", "ANIO": 2014, "MES": 3, "MES_NAME": "MARZO", "COD_CONCEPTO": "121", "VALOR": 2875, "AFECTO": "AFECTO" }, { "COD_TRAB": "067552", "TRABAJADOR": "ECHEVARRIA JESUS PAULIÑHO ", "ANIO": 2014, "MES": 3, "MES_NAME": "MARZO", "COD_CONCEPTO": "201", "VALOR": 75, "AFECTO": "AFECTO" }, { "COD_TRAB": "067552", "TRABAJADOR": "ECHEVARRIA JESUS PAULIÑHO ", "ANIO": 2014, "MES": 3, "MES_NAME": "MARZO", "COD_CONCEPTO": "303", "VALOR": 190, "AFECTO": "AFECTO" }, { "COD_TRAB": "067552", "TRABAJADOR": "ECHEVARRIA JESUS PAULIÑHO ", "ANIO": 2014, "MES": 3, "MES_NAME": "MARZO", "COD_CONCEPTO": "114", "VALOR": 1869, "AFECTO": "AFECTO" }, { "COD_TRAB": "067552", "TRABAJADOR": "ECHEVARRIA JESUS PAULIÑHO ", "ANIO": 2014, "MES": 3, "MES_NAME": "MARZO", "COD_CONCEPTO": "407", "VALOR": 1523.34, "AFECTO": "NO AFECTO" }, { "COD_TRAB": "067552", "TRABAJADOR": "ECHEVARRIA JESUS PAULIÑHO ", "ANIO": 2014, "MES": 3, "MES_NAME": "MARZO", "COD_CONCEPTO": "904", "VALOR": 1478.01, "AFECTO": "NO AFECTO" }]