//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Data.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTAMENTO
    {
        public DEPARTAMENTO()
        {
            this.PROVINCIAs = new HashSet<PROVINCIA>();
        }
    
        public int idDepartamento { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<PROVINCIA> PROVINCIAs { get; set; }
    }
}
