//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Data.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISTRITO
    {
        public DISTRITO()
        {
            this.PERSONAs = new HashSet<PERSONA>();
        }
    
        public int idDistrito { get; set; }
        public int idProvincia { get; set; }
        public string Nombre { get; set; }
    
        public virtual PROVINCIA PROVINCIA { get; set; }
        public virtual ICollection<PERSONA> PERSONAs { get; set; }
    }
}
