//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Data.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADOS_SOLICITUDTERCERO
    {
        public ESTADOS_SOLICITUDTERCERO()
        {
            this.SOLICITUDTERCEROes = new HashSet<SOLICITUDTERCERO>();
        }
    
        public int idEstadoSolicitudTercero { get; set; }
        public string DescEstado { get; set; }
    
        public virtual ICollection<SOLICITUDTERCERO> SOLICITUDTERCEROes { get; set; }
    }
}
