//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Data.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTO
    {
        public EVENTO()
        {
            this.REGISTROEVENTOes = new HashSet<REGISTROEVENTO>();
        }
    
        public int idEvento { get; set; }
        public string DescEvento { get; set; }
    
        public virtual ICollection<REGISTROEVENTO> REGISTROEVENTOes { get; set; }
    }
}
