//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Data.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONAJURIDICA
    {
        public int idPersonaJuridica { get; set; }
        public Nullable<int> idPersona { get; set; }
        public string RazonSocial { get; set; }
        public string RUC { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
    }
}
