//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Data.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONA
    {
        public PERSONA()
        {
            this.QUEJARECLAMOes = new HashSet<QUEJARECLAMO>();
            this.PERSONAJURIDICAs = new HashSet<PERSONAJURIDICA>();
            this.PERSONANATURALs = new HashSet<PERSONANATURAL>();
            this.EMPLEADO = new HashSet<EMPLEADO>();
            this.SUGERENCIA = new HashSet<SUGERENCIA>();
        }
    
        public int idPersona { get; set; }
        public Nullable<int> idDistrito { get; set; }
        public Nullable<int> idTipoDocIdentidad { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
    
        public virtual DISTRITO DISTRITO { get; set; }
        public virtual TIPODOCUMENTOIDENTIDAD TIPODOCUMENTOIDENTIDAD { get; set; }
        public virtual ICollection<QUEJARECLAMO> QUEJARECLAMOes { get; set; }
        public virtual ICollection<PERSONAJURIDICA> PERSONAJURIDICAs { get; set; }
        public virtual ICollection<PERSONANATURAL> PERSONANATURALs { get; set; }
        public virtual ICollection<EMPLEADO> EMPLEADO { get; set; }
        public virtual ICollection<SUGERENCIA> SUGERENCIA { get; set; }
    }
}
