//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Data.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUEJARECLAMO
    {
        public QUEJARECLAMO()
        {
            this.HOJARESPUESTA = new HashSet<HOJARESPUESTA>();
            this.REGISTROEVENTO = new HashSet<REGISTROEVENTO>();
            this.SOLICITUDTERCERO = new HashSet<SOLICITUDTERCERO>();
        }
    
        public int idQuejaReclamo { get; set; }
        public Nullable<int> idPersona { get; set; }
        public string NroRegistro { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string Hora { get; set; }
        public string Asunto { get; set; }
        public string Descripcion { get; set; }
        public string ArchivoAdjunto { get; set; }
        public Nullable<int> UsrRegistro { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<int> idEstadoQuejaReclamo { get; set; }
        public Nullable<int> UsrModifica { get; set; }
        public Nullable<System.DateTime> FecModifica { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
        public virtual ICollection<HOJARESPUESTA> HOJARESPUESTA { get; set; }
        public virtual ICollection<REGISTROEVENTO> REGISTROEVENTO { get; set; }
        public virtual ICollection<SOLICITUDTERCERO> SOLICITUDTERCERO { get; set; }
        public virtual ESTADOS_QUEJARECLAMO ESTADOS_QUEJARECLAMO { get; set; }
    }
}
