//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Data.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTROEVENTO
    {
        public int idRegistroEvento { get; set; }
        public Nullable<int> idArea { get; set; }
        public Nullable<int> idQuejaReclamo { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> UsrRegistra { get; set; }
        public Nullable<System.DateTime> FecRegistra { get; set; }
        public Nullable<int> UsrModifica { get; set; }
        public Nullable<System.DateTime> FecModifica { get; set; }
        public Nullable<int> idEvento { get; set; }
    
        public virtual QUEJARECLAMO QUEJARECLAMO { get; set; }
        public virtual AREA AREA { get; set; }
        public virtual EVENTO EVENTO { get; set; }
    }
}
