//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Data.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUDTERCERO
    {
        public SOLICITUDTERCERO()
        {
            this.INFORMETERCERO = new HashSet<INFORMETERCERO>();
        }
    
        public int idSolicitudTercero { get; set; }
        public Nullable<int> idQuejaReclamo { get; set; }
        public Nullable<int> idTercero { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string DescSolicitud { get; set; }
        public Nullable<int> UsrRegistra { get; set; }
        public Nullable<System.DateTime> FecRegistra { get; set; }
        public Nullable<int> UsrModifica { get; set; }
        public Nullable<System.DateTime> FecModifica { get; set; }
        public Nullable<int> idEstadoSolicitudTercero { get; set; }
    
        public virtual ICollection<INFORMETERCERO> INFORMETERCERO { get; set; }
        public virtual QUEJARECLAMO QUEJARECLAMO { get; set; }
        public virtual TERCERO TERCERO { get; set; }
        public virtual ESTADOS_SOLICITUDTERCERO ESTADOS_SOLICITUDTERCERO { get; set; }
    }
}
