//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Data.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUGERENCIA
    {
        public int idSugerencia { get; set; }
        public Nullable<int> idPersona { get; set; }
        public string NroSugerencia { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string Hora { get; set; }
        public string Asunto { get; set; }
        public string Descripcion { get; set; }
        public string ArchivoAdjunto { get; set; }
        public Nullable<int> EstadoNotificacion { get; set; }
        public Nullable<int> UsrRegistra { get; set; }
        public Nullable<System.DateTime> FecRegistra { get; set; }
        public Nullable<int> UsrModifica { get; set; }
        public Nullable<System.DateTime> FecModifica { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
    }
}
