//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Data.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TERCERO
    {
        public TERCERO()
        {
            this.SOLICITUDTERCERO = new HashSet<SOLICITUDTERCERO>();
        }
    
        public int idTercero { get; set; }
        public string RazonSocial { get; set; }
        public string Ruc { get; set; }
        public string DireccionFiscal { get; set; }
        public Nullable<int> UsrRegistra { get; set; }
        public Nullable<System.DateTime> FecRegistra { get; set; }
        public Nullable<int> UsrModifica { get; set; }
        public Nullable<System.DateTime> FecModifica { get; set; }
    
        public virtual ICollection<SOLICITUDTERCERO> SOLICITUDTERCERO { get; set; }
    }
}
